# Generated by Django 4.2.1 on 2023-08-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('work', models.CharField(default='null', max_length=400)),
                ('isComplete', models.BooleanField(default=False)),
            ],
        ),
    ]
